### ISSUE TITLE
Android Studio 3.3 and gradle plugin 3.3.0 wont compile

### ISSUE THREAD

**Issue by barnhill** [prolificinteractive/material-calendarview#917]
To get a project consuming this library to work in AS3.3 with gradle plugin 3.3.0 you have to use the following in your build.gradle.

implementation ("com.github.prolificinteractive:material-calendarview:2.0.0") {
            exclude group: 'org.threeten', module: 'threetenbp'
        }
        implementation 'org.threeten:threetenbp:1.3.8'

**Comment by barnhill** [comment]
If you would accept a PR for this Id be fine creating it to update the dependency

**Comment by artnest** [comment]
Also works without excluding ThreeTenABP.

**Comment by barnhill** [comment]
Yea I think it's just the update of the dependency

**Comment by barnhill** [comment]
@quentin41500 want me to throw together a pull request to address this?  Should just be a single dependency update from 1.1.0 to 1.1.1 of threetenabp

**Comment by quentin41500** [comment]
@barnhill go for it, I'll review as soon as I can

**Comment by barnhill** [comment]
For documentation purposes here is the compilation error that I get without this change Im about to make.

<img width="526" alt="screen shot 2019-01-22 at 7 36 10 pm" src="https://user-images.githubusercontent.com/3878158/51576746-0bd89780-1e7d-11e9-9046-38219755f2ed.png">

**Comment by barnhill** [comment]
Link to Pull Request: https://github.com/prolificinteractive/material-calendarview/pull/920

**Comment by quentin41500** [comment]
https://github.com/prolificinteractive/material-calendarview/releases/tag/2.0.1 Please let me know if there is any issues with the pre-release before I do the full release.

**Comment by barnhill** [comment]
Im still running into a need to include "com.jakewharton.threetenabp:threetenabp:1.1.1" in my dependencies.  Something is still up Im afraid.

**Comment by barnhill** [comment]
@quentin41500 

Here is what Im seeing right now.  When I import material-calendarview using:
implementation "com.github.prolificinteractive:material-calendarview:2.0.1"

This is the error I get on compilation.

`error: cannot access LocalDate
                calendarView.setCurrentDate(CalendarDay.today());
                            ^
  class file for org.threeten.bp.LocalDate not found
`

Here is a look at the dependencies for the app (or atleast a segment):

+--- com.github.prolificinteractive:material-calendarview:2.0.1
|    +--- com.jakewharton.threetenabp:threetenabp:1.1.1
|    |    \--- org.threeten:threetenbp:1.3.7


I have to also include:
implementation "org.threeten:threetenbp:1.3.8:no-tzdb"

for it to compile.  Ive tried a lot of different things and am coming up empty.  Let me know if you have any ideas on how to not have to include this in my gradle since it should be brought in as a transitive dependency of your library.

**Comment by quentin41500** [comment]
I haven't check, but we are not leaking threeTenABP on purpose. If you want to access LocalDate and use the object, we do recommend that you add the library.

In the sample, you can see we added:
```
  implementation rootProject.ext.threeTenAbp
```

**Comment by barnhill** [comment]
@quentin41500 we arent using it though.  Its on the call to calendarView.setCurrentDate(CalendarDay.today());

**Comment by barnhill** [comment]
@quentin41500  its interesting that this isnt required unless I update our application to Gradle 5+.  On 4.10.2 its fine.
